import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React, {useEffect, useState} from "react"
import OneSignal from 'react-onesignal';

// OneSignal.init({ appId: '59494dfb-bf56-4e3d-a8be-73e3c143a9b5' }).then(() => {
//   setInitialized(true);
//   OneSignal.Slidedown.promptPush();
//   // do other stuff
// });

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [resultApi, setResultApi] = useState();
  useEffect(() => {
    window.OneSignal = window.OneSignal || [];
    OneSignal.push(function () {
      OneSignal.init({
        appId: "59494dfb-bf56-4e3d-a8be-73e3c143a9b5",
        notifyButton: {
          enable: true,
        },

        allowLocalhostAsSecureOrigin: true,
      });
    });
    return () => {
      window.OneSignal = undefined;
    };
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" 
async="">
    </script>
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
            <h1>LEAP</h1>
            <h2>Leap before you learn!</h2>
        </div>
      </main>
    </>
  );
}
